<a href="https://colab.research.google.com/github/DuvallRob/Coding-Practice-DocumentIntelligence/blob/main/Bank_Loan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
#Reads and Displays bank_loan.csv file
bank_data = pd.read_csv("/kaggle/input/bank-personal-loan/bank_loan.csv")
bank_data

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91108,4,1/60,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1/50,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1/00,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2/70,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1/00,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,29,3,40,92697,1,1/90,3,0,0,0,0,1,0
4996,4997,30,4,15,92037,4,0/40,1,85,0,0,0,1,0
4997,4998,63,39,24,93023,2,0/30,3,0,0,0,0,0,0
4998,4999,65,40,49,90034,3,0/50,2,0,0,0,0,1,0
4999,5000,28,4,83,92612,3,0/80,1,0,0,0,0,1,1

In [ ]:
#Displays first 5 records
bank_data.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91108,4,1/60,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1/50,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1/00,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2/70,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1/00,2,0,0,0,0,0,1

In [ ]:
#Displays first 10 records
bank_data.head(10)

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91108,4,1/60,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1/50,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1/00,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2/70,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1/00,2,0,0,0,0,0,1
5,6,37,13,29,92121,4,0/40,2,155,0,0,0,1,0
6,7,53,27,72,91711,2,1/50,2,0,0,0,0,1,0
7,8,50,24,22,93943,1,0/30,3,0,0,0,0,0,1
8,9,35,10,81,90089,3,0/60,2,104,0,0,0,1,0
9,10,34,9,180,93023,1,8/90,3,0,1,0,0,0,0

In [ ]:
#Shows last 5 records
bank_data.tail()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
4995,4996,29,3,40,92697,1,1/90,3,0,0,0,0,1,0
4996,4997,30,4,15,92037,4,0/40,1,85,0,0,0,1,0
4997,4998,63,39,24,93023,2,0/30,3,0,0,0,0,0,0
4998,4999,65,40,49,90034,3,0/50,2,0,0,0,0,1,0
4999,5000,28,4,83,92612,3,0/80,1,0,0,0,0,1,1

In [ ]:
bank_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   object
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: int64(13), object(1)
memory usage: 547.0+ KB

In [ ]:
#Dimensions of the dataframe
bank_data.shape

(5000, 14)

In [ ]:
#Data type of each column
bank_data.dtypes

ID                     int64
Age                    int64
Experience             int64
Income                 int64
ZIP Code               int64
Family                 int64
CCAvg                 object
Education              int64
Mortgage               int64
Personal Loan          int64
Securities Account     int64
CD Account             int64
Online                 int64
CreditCard             int64
dtype: object

In [ ]:
#Detects sum of all null types in the dataframe
bank_data.isna().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [ ]:
bank_data.describe()

,ID,Age,Experience,Income,ZIP Code,Family,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,2500.500000,45.338400,20.104600,73.774200,93152.503200,2.396400,1.881000,56.498800,0.096000,0.104400,0.06040,0.596800,0.294000
std,1443.520003,11.463166,11.467954,46.033729,2121.852005,1.147663,0.839869,101.713802,0.294621,0.305809,0.23825,0.490589,0.455637
min,1.000000,23.000000,-3.000000,8.000000,9307.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,64.000000,93437.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,98.000000,94608.000000,3.000000,3.000000,101.000000,0.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,67.000000,43.000000,224.000000,96651.000000,4.000000,3.000000,635.000000,1.000000,1.000000,1.00000,1.000000,1.000000

In [ ]:
#Filtering rows with Income higher than 100rs
filtered_data = bank_data[bank_data['Income'] > 100]
filtered_data

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
9,10,34,9,180,93023,1,8/90,3,0,1,0,0,0,0
10,11,65,39,105,94710,4,2/40,3,0,0,0,0,0,0
12,13,48,23,114,93106,2,3/80,3,0,0,1,0,0,0
14,15,67,41,112,91741,1,2/00,1,0,0,1,0,0,0
16,17,38,14,130,95010,4,4/70,3,134,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4962,4963,46,20,122,90065,3,3/00,3,0,1,0,1,1,1
4964,4965,53,27,110,90245,1,4/90,1,0,0,0,0,1,0
4980,4981,29,5,135,95762,3,5/30,1,0,1,0,1,1,1
4981,4982,34,9,195,90266,2,3/00,1,122,0,0,0,1,0
4993,4994,45,21,218,91801,2,6/67,1,0,0,0,0,1,0

In [ ]:
#Sorting based on Age
sorted_data = bank_data.sort_values(by='Age', ascending=True)
sorted_data

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
3130,3131,23,-2,82,92152,2,1/80,2,0,0,1,0,0,1
3157,3158,23,-1,13,94720,4,1/00,1,84,0,0,0,1,0
670,671,23,-1,61,92374,4,2/60,1,239,0,0,0,1,0
3425,3426,23,-1,12,91605,4,1/00,1,90,0,0,0,1,0
2962,2963,23,-2,81,91711,2,1/80,2,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2846,2847,67,43,105,93711,4,1/70,2,0,0,0,0,1,0
3264,3265,67,41,114,95616,4,2/40,3,0,0,0,0,1,0
3331,3332,67,42,21,94607,3,0/10,3,0,0,0,0,0,1
1859,1860,67,41,20,91741,2,0/40,1,80,0,0,0,0,0
1480,1481,67,42,32,93943,1,1/10,3,0,0,0,0,0,1

In [ ]:
#Sum of all values income
int(bank_data['Income'].sum())

368871

In [ ]:
#Mean of values income
int(bank_data['Income'].mean())

73

In [ ]:
#Median of values income
bank_data['Income'].median()

64.0

In [ ]:
#Mode of values income
bank_data['Income'].mode()

0    44
Name: Income, dtype: int64

In [ ]:
#find count of rows with income greater than 100rs
income_count = bank_data[bank_data['Income'] > 100].count()
print(income_count)

ID                    1212
Age                   1212
Experience            1212
Income                1212
ZIP Code              1212
Family                1212
CCAvg                 1212
Education             1212
Mortgage              1212
Personal Loan         1212
Securities Account    1212
CD Account            1212
Online                1212
CreditCard            1212
dtype: int64

In [ ]:
#group data based on education
grouped_data = bank_data.groupby('Experience')
grouped_data.first()

,ID,Age,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
Experience,,,,,,,,,,,,,
-3,2619,23,55,92704,3,2/40,2,145,0,0,0,1,0
-2,316,24,51,90630,3,0/30,3,0,0,0,0,1,0
-1,90,25,113,94303,4,2/30,3,0,0,0,0,0,1
0,106,24,35,94704,3,0/10,2,0,0,1,0,1,0
1,1,25,49,91108,4,1/60,1,0,0,1,0,0,0
2,59,28,93,94065,2,0/20,1,0,0,0,0,0,0
3,75,28,135,94611,2,3/30,1,0,0,0,0,0,1
4,131,28,81,94801,3,1/50,1,276,0,0,0,1,0
5,12,29,45,90277,3,0/10,2,0,0,0,0,1,0
6,34,30,18,91330,3,0/90,3,0,0,0,0,0,0
7,43,32,132,90019,4,1/10,2,412,1,0,0,1,0
8,5,35,45,91330,4,1/00,2,0,0,0,0,0,1
9,4,35,100,94112,1,2/70,2,0,0,0,0,0,0
10,9,35,81,90089,3,0/60,2,104,0,0,0,1,0
11,25,36,152,95521,2,3/90,1,159,0,0,0,0,1
12,48,37,194,91380,4,0/20,3,211,1,1,1,1,1
13,6,37,29,92121,4,0/40,2,155,0,0,0,1,0
14,17,38,130,95010,4,4/70,3,134,1,0,0,0,0
15,3,39,11,94720,1,1/00,1,0,0,0,0,0,0
16,27,40,83,95064,4,0/20,3,0,0,0,0,0,0
17,56,41,139,94022,2,8/00,1,0,0,0,0,1,0
18,18,42,81,94305,4,2/40,1,0,0,0,0,0,0
19,2,45,34,90089,3,1/50,1,0,0,1,0,0,0
20,28,46,158,90064,1,2/40,1,0,0,0,0,1,1
21,19,46,193,91604,2,8/10,3,0,1,0,0,0,0
22,82,47,40,94612,3,2/70,2,0,0,0,0,1,0
23,13,48,114,93106,2,3/80,3,0,0,1,0,0,0
24,8,50,22,93943,1,0/30,3,0,0,0,0,0,1
25,38,51,71,95814,1,1/40,3,198,0,0,0,0,0
26,49,56,81,95747,2,4/50,3,0,0,0,0,0,1
27,7,53,72,91711,2,1/50,2,0,0,0,0,1,0
28,20,55,21,94720,1,0/50,2,0,0,1,0,0,1
29,70,53,20,90045,4,0/20,1,0,0,0,0,1,0
30,16,60,22,95054,1,1/50,3,0,0,0,0,1,1
31,21,56,25,94015,4,0/90,2,111,0,0,0,1,0
32,14,59,40,94920,4,2/50,2,0,0,0,0,1,0
33,118,58,61,92833,2,2/30,3,193,0,0,0,1,0
34,94,60,64,94550,2,1/70,3,236,0,1,0,1,0
35,31,59,35,93106,1,1/20,3,122,0,0,0,1,0
36,67,62,105,95670,2,2/80,1,336,0,0,0,0,0
37,52,61,131,94720,1,2/90,1,0,0,0,0,1,0
38,112,62,45,94143,4,1/30,2,0,0,0,0,1,0
39,11,65,105,94710,4,2/40,3,0,0,0,0,0,0
40,116,65,81,92024,3,1/80,2,0,0,0,0,1,0
41,15,67,112,91741,1,2/00,1,0,0,1,0,0,0
42,466,66,35,94305,1,1/90,2,172,0,0,0,1,0
43,2847,67,105,93711,4,1/70,2,0,0,0,0,1,0